# This is a service message that exposes the Fast Robot Interface's (FRI)
# KUKA::FRI::ClientApplication::connect method to a service call.
#
# Following states are exposes (also refer to KUKA::FRI::LBRState in friLBRState.h)
#
#  * port [int32]: The port ID.
#  * remote_host [string]: The address of the remote host.
#  ---
#  * established [bool]: True when connection established successfully.

int32 port_id
string remote_host
---
bool established
