# This service message is used to call the Fast Robot Interface's (FRI)
# KUKA::FRI::ClientApplication::connect method via a service call.
#
#  * port [int32]: The port ID.
#  * remote_host [string]: The address of the remote host.
#  ---
#  * connected [bool]: True when connection established successfully.
#  * message [string]: Informational message, containing e.g. errors.

int32 port_id
string remote_host
uint8 rt_prio
uint8 max_attempts
---
bool connected
string message
